version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/archlinux/index/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependency Updates"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions Updates"
