#!/bin/bash

set -e

for directory in ./repo/*/; do
    if [ ! -f "${directory}build" ]; then
        echo "No build script found under $directory, skipping"
        continue
    fi

    repo_name=$(basename "$directory")

    echo "Executing ${directory}build"
    "${directory}build"

    echo "Copying files from ${directory}staging/"
    mkdir -p "./staging/$repo_name/"
    cp -v -r "${directory}staging/." "./staging/$repo_name/"

    echo
done
