name: Build and Publish Repository
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Setup Python dependencies
        run: |
          pip3 install -r ./archlinux/index/requirements.txt
      - name: Executing build script
        run: |
          ./build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './staging'
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
